config/routes.rb
Rails.application.routes.draw do
  resources :metals
  resources :golds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/" , to: "static#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gold.rb
class Gold < ApplicationRecord
end

app/models/metal.rb
class Metal < ApplicationRecord
end

app/models/silver.rb
class Silver < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/golds_controller.rb
class GoldsController < ApplicationController
  before_action :set_gold, only: [:show, :edit, :update, :destroy]

  # GET /golds
  # GET /golds.json
  def index
    @golds = Gold.all
    respond_to do |format|
      format.html do
      end
    end
  end

  # GET /golds/1
  # GET /golds/1.json
  def show
    puts "hello world"
  end

  # GET /golds/new
  def new
    @gold = Gold.new
  end

  # GET /golds/1/edit
  def edit
  end

  # POST /golds
  # POST /golds.json
  def create
    @gold = Gold.new(gold_params)

    respond_to do |format|
      if @gold.save
        format.html { redirect_to @gold, notice: 'Gold was successfully created.' }
        format.json { render :show, status: :created, location: @gold }
      else
        format.html { render :new }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /golds/1
  # PATCH/PUT /golds/1.json
  def update
    respond_to do |format|
      if @gold.update(gold_params)
        format.html { redirect_to @gold, notice: 'Gold was successfully updated.' }
        format.json { render :show, status: :ok, location: @gold }
      else
        format.html { render :edit }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golds/1
  # DELETE /golds/1.json
  def destroy
    @gold.destroy
    respond_to do |format|
      format.html { redirect_to golds_url, notice: 'Gold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold
      @gold = Gold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gold_params
      params.require(:gold).permit(:title, :body)
    end
end

app/controllers/metals_controller.rb
class MetalsController < ApplicationController
  before_action :set_metal, only: [:show, :edit, :update, :destroy]

  # GET /metals
  # GET /metals.json
  def index
    @name = params[:name]
    @metals = Metal.all
    if cookies[:visited]
      response.set_cookie(:visited,
        :value => cookies[:visited].to_i + 1
      )
    else
        @show_message = true;
        # set the visited cookie
        response.set_cookie(:visited,
                            :value => 1,
                            :expires => Time.now + (60 * 60 * 2)
                           )

      end
  end

  # GET /metals/1
  # GET /metals/1.json
  def show
      if cookies[:show]
        response.set_cookie(:show,
          :value => cookies[:show].to_i + 1
        )
      else
        @show_message = true;
        # set the visited cookie
        response.set_cookie(:show,
                            :value => 1,
                            :expires => Time.now + (60 * 60 * 2)
                           )

      end
  end

  # GET /metals/new
  def new
    @metal = Metal.new
  end

  # GET /metals/1/edit
  def edit
  end

  # POST /metals
  # POST /metals.json
  def create
    @metal = Metal.new(metal_params)
    respond_to do |format|
      if @metal.save
        if cookies[:new]
          response.set_cookie(:new,
            :value => cookies[:new].to_i + 1
          )
        else
          @show_message = true;
          # set the visited cookie
          response.set_cookie(:new,
                              :value => 1,
                              :expires => Time.now + (60 * 60 * 2)
                             )

        end
        format.html { redirect_to @metal, notice: 'Metal was successfully created.' }
        format.json { render :show, status: :created, location: @metal }
      else
        format.html { render :new }
        format.json { render json: @metal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metals/1
  # PATCH/PUT /metals/1.json
  def update
    if cookies[:edit]
      response.set_cookie(:edit,
        :value => cookies[:edit].to_i + 1
      )
    else
      @show_message = true;

      # set the visited cookie
      response.set_cookie(:edit,
                          :value => 1,
                          :expires => Time.now + (60 * 60 * 2)
                         )

    end
    respond_to do |format|
      if @metal.update(metal_params)
        format.html { redirect_to @metal, notice: 'Metal was successfully updated.' }
        format.json { render :show, status: :ok, location: @metal }
      else
        format.html { render :edit }
        format.json { render json: @metal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metals/1
  # DELETE /metals/1.json
  def destroy
    if cookies[:destroy]
      response.set_cookie(:destroy,
        :value => cookies[:destroy].to_i + 1
      )
    else
      @show_message = true;

      # set the visited cookie
      response.set_cookie(:destroy,
                          :value => 1,
                          :expires => Time.now + (60 * 60 * 2)
                         )
    end
    @metal.destroy
    respond_to do |format|
      format.html { redirect_to metals_url, notice: 'Metal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metal
      @metal = Metal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metal_params
      params.require(:metal).permit(:title, :body)
    end
end

app/controllers/silvers_controller.rb
class SilversController < ApplicationController

silvers = {
    id: 0,
    title: "18ct",
    unit: "lbs",
    price: "$1253"
  }

  def index
    @silver = silvers
    respond_to do |format|
      format.html do
      end
    end
  end

  def new

  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :set_gold, only: [:show, :edit, :update, :destroy]

  # GET /golds
  # GET /golds.json
  def index
    @static_name = params[:name]
    respond_to do |format|
      format.html do
      end
    end
  end

  # GET /golds/1
  # GET /golds/1.json
  def show
  end

  # GET /golds/new
  def new
    @gold = Gold.new
  end

  # GET /golds/1/edit
  def edit
  end

  # POST /golds
  # POST /golds.json
  def create
    @gold = Gold.new(gold_params)

    respond_to do |format|
      if @gold.save
        format.html { redirect_to @gold, notice: 'Gold was successfully created.' }
        format.json { render :show, status: :created, location: @gold }
      else
        format.html { render :new }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /golds/1
  # PATCH/PUT /golds/1.json
  def update
    respond_to do |format|
      if @gold.update(gold_params)
        format.html { redirect_to @gold, notice: 'Gold was successfully updated.' }
        format.json { render :show, status: :ok, location: @gold }
      else
        format.html { render :edit }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golds/1
  # DELETE /golds/1.json
  def destroy
    @gold.destroy
    respond_to do |format|
      format.html { redirect_to golds_url, notice: 'Gold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold
      @gold = Gold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gold_params
      params.require(:gold).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/golds_helper.rb
module GoldsHelper
end

app/helpers/metals_helper.rb
module MetalsHelper
end

app/views/golds/_form.html.erb
<%= form_with(model: gold, local: true) do |form| %>
  <% if gold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gold.errors.count, "error") %> prohibited this gold from being saved:</h2>

      <ul>
      <% gold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/golds/edit.html.erb
<h1>Editing Gold</h1>

<%= render 'form', gold: @gold %>

<%= link_to 'Show', @gold %> |
<%= link_to 'Back', golds_path %>

app/views/golds/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Gold</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @golds.each do |gold| %>
      <tr>
        <td><%= gold.title %></td>
        <td><%= gold.body %></td>
        <td><%= link_to 'Show', gold %></td>
        <td><%= link_to 'Edit', edit_gold_path(gold) %></td>
        <td><%= link_to 'Destroy', gold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gold', new_gold_path %>

app/views/golds/new.html.erb
<h1>New Gold</h1>

<%= render 'form', gold: @gold %>

<%= link_to 'Back', golds_path %>

app/views/golds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gold.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @gold.body %>
</p>

<%= link_to 'Edit', edit_gold_path(@gold) %> |
<%= link_to 'Back', golds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mani's Resources</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="jumbotron text-center bg-info">Welcome to Mani's resources</h1>
    <br>
    <%= yield %>
  </body>
</html>

app/views/metals/_form.html.erb
<%= form_with(model: metal, local: true) do |form| %>
  <% if metal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metal.errors.count, "error") %> prohibited this metal from being saved:</h2>

      <ul>
      <% metal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/metals/edit.html.erb
<h1>Editing Metal</h1>

<%= render 'form', metal: @metal %>

<%= link_to 'Show', @metal %> |
<%= link_to 'Back', metals_path %>

app/views/metals/index.html.erb
<div class="text-center">
  <h1 class="display-3">Metals</h1>
  <p id="notice"><%= notice %></p>
  <div class="panel d-flex justify-content-center">




    <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Price per kg</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @metals.each do |metal| %>
          <tr>
            <td ><%= metal.title %></td>
            <td><%= metal.body %></td>
            <td><%= link_to 'Show', metal %></td>
            <td><%= link_to 'Edit', edit_metal_path(metal) %></td>
            <td><%= link_to 'Destroy', metal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <br>
  <button type="button" name="button"><%= link_to 'New Metal', new_metal_path %></button>
  <button type="button" name="button"><%= link_to 'Index', "/" %></button>

</div>

<br>

<div class="panel text-center">
  <button class="btn-info" type="button" name="button">
    <p>So far you have:</p>
    <p>Visited the homepage =
      <%=cookies[:visited]%>
      times</p>
    <p>Viewed the metals resources =
      <%=cookies[:show]%>
      times</p>
    <p>Created
      <%=cookies[:new]%>
      new items</p>
    <p>Edited
      <%=cookies[:edit]%>
      items</p>
    <p>Deleted
      <%=cookies[:destroy]%>
      items</p>
  </button>

</div>

app/views/metals/new.html.erb
<h1>New Metal</h1>

<%= render 'form', metal: @metal %>

<%= link_to 'Back', metals_path %>

<%= link_to 'Home', metals_path %>

app/views/metals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @metal.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @metal.body %>
</p>

<%= link_to 'Edit', edit_metal_path(@metal) %> |
<%= link_to 'Back', metals_path %>
<%= link_to 'Home', metals_path %>

app/views/silvers/form.html.erb
<form class="" action="/<%=@silver.id%>" method="post">
  <label for="">ID</label>
  <input type="text" name="id" value="<%=@silver.id%>">
  <br>
  <label for="">Title</label>
  <input type="text" name="name" value="<%=@silver.title%>">
  <br>
  <label for="">Body</label>
  <input type="text" name="id" value="<%=@silver.body%>">
  <br>
  <input href="/" type="submit" name="submit" value="submit">
  <% if @silver.id != "" %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>
</form>

app/views/silvers/index.html.erb
<h1>Welcome to Silvers</h1>

<a href="/silvers/new">create a new silver?</a>

app/views/silvers/new.html.erb
<h1>Create a new class of silver here!</h1>

<input type="text" name="" value="">